### ISSUE TITLE
室内表面熱伝達率の扱い

### ISSUE THREAD

**Issue by satoh-er** [BRI-EES-House/heat_load_calc#24]
# 概要
（境界の室内側総合熱伝達率、対流熱伝達率、放射熱伝達率の関係を整理する）

# タスク
- [ ] （ここにタスクを記す）
- [ ] （ここにタスクを記す）

# 参考情報
（ここに添付ファイル・画像・URL等を貼り付ける）

**Comment by HisashiMiura** [comment]
@satoh-er これってなんでしたっけ？もしよければ、もう少し詳しい情報をお願いします！

**Comment by satoh-er** [comment]
@HisashiMiura 
現状、室内側表面総合熱伝達率が部位によって固定とされています。
永田先生の方法で求めた放射熱伝達率を総合熱伝達率から引いた残差を対流熱伝達率としています。
部位ごとに対流熱伝達率を固定し、永田先生の方法で求めた放射熱伝達率を足して総合熱伝達率にするのが正しいと思いました。
ということです。

**Comment by HisashiMiura** [comment]
@satoh-er 
主旨はわかりました！
・・・が、現行、省エネ基準では、総合熱伝達率しか定義がないため、対流熱伝達率（固定値）をいくらにすべきと思いますか？なんか一般的な値ってあるんでしたっけ？

**Comment by satoh-er** [comment]
@HisashiMiura 
空調便覧の１基礎篇P89には、放射熱伝達率は5W/m2K程度と記述されています。
弊社がシミュレーションするときには、省エネ基準で決められた総合熱伝達率から、上記の放射熱伝達率5W/m2Kを引いた残りを対流熱伝達率として入力し、シミュレーション内部で求められた放射熱伝達率との合計を総合熱伝達率としています。

**Comment by HisashiMiura** [comment]
@satoh-er 了解です！
では、省エネ基準で決められた総合熱伝達率から、放射熱伝達率として何か固定値を引き、残りを固定値としての対流熱伝達率とする。その上で、負荷計算上の放射熱伝達率は永田先生の式に依存する。としたいと思います。
「省エネ基準で決められた総合熱伝達率から、放射熱伝達率として何か固定値を引き」の部分の「固定値」については、特に良いアイデアなければ5W/m2Kで良いかと思いますが、軽く、過去の省エネ基準の解説書等を紐解き、値設定の根拠を確認したほうが良いですね。おそらく、何らかの想定があるのでは？と思っています。

**Comment by satoh-er** [comment]
@HisashiMiura 
室内表面の熱伝達率は対流熱伝達率のみを指定するように修正。
ただし、裏面の熱伝達率は以下のように扱うこととする。
１）外皮：総合熱伝達率を指定する
２）内壁：対流熱伝達率を指定する
