### ISSUE TITLE
床の判定

### ISSUE THREAD

**Issue by satoh-er** [BRI-EES-House/heat_load_calc#27]
# 概要
（室内部位と人体の形態係数は床を45%、残りを面積比で案分しています。
床の判定は「is_solar_absorbed_inside_i_jstrs」で行っています。
今回のプログラムでは日射を床に吸収させますが、なんとなく分けたほうがいいのかなぁと思いました。）

# タスク
- [ ] （ここにタスクを記す）
- [ ] （ここにタスクを記す）

# 参考情報
（ここに添付ファイル・画像・URL等を貼り付ける）

**Comment by HisashiMiura** [comment]
@satoh-er 
確かにそうですね。僕も現象が違うことは（ほとんどの場合で一致することでも）分けた方が良いと思います。
後で、
"is_floor" みたいな key を追加しておきます。
