### ISSUE TITLE
壁体の集約方法について再整理する

### ISSUE THREAD

**Issue by HisashiMiura** [BRI-EES-House/heat_load_calc#41]
# 概要
現在、以下の項目が同じであることをもって壁体の集約を可能としている。
- 境界の種類
- 室内侵入日射吸収の有無

境界の種類が「外皮_一般部位」、「外皮_透明な開口部」又は「外皮_不透明な開口部」の場合
- 日射の有無
- 温度差係数
- 日射があたる場合において 方位
境界の種類が間仕切りの場合
- 隣室のタイプ

- 室内側熱伝達抵抗

外気に面している場合
- 室外側長波長放射率
- 室外側日射吸収率

# タスク
- [ ] 上記の方法でよいか、今一度、整理する。

# 参考情報
https://github.com/BRI-EES-House/heat_load_calc/blob/master/heat_load_calc/a34_building_part_summarize.py

**Comment by HisashiMiura** [comment]
@satoh-er 1点相談です。
統合できるものは統合し、統合できないものは統合しない。という方針だったかと思います。
・・・と思って、今、再整理しているのですが、
室外側の等価外気温度については、個々の壁面で計算し、それを面積加重平均をするという方針を採用しています。
となると、ぎちぎちと統合化をするのであれば、上記の、
・方位
・日射の有無
については、別に違っていても統合化しても構わないのでは？と思い始めてきました。
ということで、この点について、ご意見いただけないでしょうか？
単なる室内に１質点系だったら平気に統合してしまって問題ないような気もしますが、一方で室内側表面温度バランスによる放射計算も解いているわけで、そこらへんで集約しすぎるとなにか悪さをしないのかな？とも思っています。
よろしくお願いします。

**Comment by satoh-er** [comment]
@HisashiMiura 
以前、永田先生にご相談したときには、室内側熱伝達率が共通であれば、裏面の相当温度を面積荷重平均して壁体の統合が可能だとおっしゃられていました。方位も壁・窓も関係なく集約できるとのことでした。
基整促E7のときは、相当外気温度が同じという前提で集約前後で室温、負荷は変わらないという検証はしましたが、相当外気温度が異なる部位の集約の検証はしていません。
懸案事項は、以下程度だと思われます。
１）室内側の放射の計算はおかしくなっていないか（同一方位であれば形態係数がゼロなので問題なし）
２）室内側部位表面温度が平均化されることの影響
いずれも、特に問題にならなそうですね。
よって、相当外気温度が異なる部位の集約前後で室温や熱負荷が変わらないことを確認すれば集約しても差し支えないと思います。
ひょっとすると、方位が違っても集約していいのかもしれません。

**Comment by HisashiMiura** [comment]
@satoh-er 
佐藤さんの意見を受けて、
- 外壁外側の日射が当たるか否か？
- 日射吸収率
- 長波長放射率
の違いについては集約するようにします。

問題は、方位が違っていても集約できるのか？です。
僕も、形態係数が気になっています。
もしかすると、方位が違っていても集約できるのかもしれませんが、とりあえず集約はしないという方針かなぁ。
と思っていますが、どうでしょうか？

**Comment by satoh-er** [comment]
@HisashiMiura 
方位が同じ部位は、お互いの形態係数が０になるのは自明ですので、集約は問題ありません。
方位が違うと、本来放射伝熱が生じるのをゼロにしてしまうので、せっかく永田理論を組み込んだのに意味がなくなってしまいます。
よって、三浦さん案に賛成です。
