### ISSUE TITLE
日よけの効果を天空放射成分にも適用する。

### ISSUE THREAD

**Issue by HisashiMiura** [BRI-EES-House/heat_load_calc#64]
# 概要
現状：直達成分にしか日よけの効果がかかっていない。
天空放射成分にも日よけの効果をかけるように追加する。

# タスク
- [x] 日よけの効果を計算するロジックを追加する。→　佐藤
- [ ] 本体に組み込む　→　三浦

**Comment by satoh-er** [comment]
日除けの効果については、西澤さん作のPythonコードをインポートする方針だったと思いますが、いかがでしょうか。

**Comment by HisashiMiura** [comment]
@satoh-er 日よけの効果の計算に、simple（横方向に無限長さを持つオーバーハング型ひよけ） と detail があります。detail の方は西澤さんのをインポートしますので、実装の必要はありません。一方、simple の方は実装しておいていただければと思います。
西澤さんのdetail が simple も兼ねる可能性はありますが、西澤さんのはそちらはそちらで無限長さでは組んでいないため、simple の値と一致した計算はでてこないかと思っています。（横方向の長さをむちゃくちゃ大きく取れば、コンマ何桁めまでの精度で一致した値は出せるとは思いますが・・・）

**Comment by satoh-er** [comment]
@HisashiMiura 
なるほど。了解しました。
無限に長い庇と窓との形態係数を求めればいいのですね。

**Comment by satoh-er** [comment]
@HisashiMiura 
計算式を整理し、Githubにアップしました。
プルリクエストを送りました。

**Comment by HisashiMiura** [comment]
@satoh-er 
[要相談] 地面反射日射についてはどのように扱うのか？　→　日よけの内側の反射は考慮していないので、単純に1.0でよいかもしれない。（simple の場合）
詳細計算では、地面反射日射の扱いについては西澤さんに確認すること。

**Comment by satoh-er** [comment]
@HisashiMiura 
地面反射日射が庇の下側に当たり、それが反射したものの扱いですか？
無視でよいので、地面反射に対する日除けの効果は1.0でよいと思います。
詳細は、西澤さんに伺っていただきたいですが、そこまでやっているんですかねぇ。
ちなみに、非住宅では下階の庇によって下階側からの反射日射が大きくなるというのをやろうとしています。

**Comment by HisashiMiura** [comment]
@satoh-er 
承知しました。地面反射については1.0としたいと思います。
下階の庇　については、確かに影響は大きいかと思います。
ただ、いきなり負荷計算プログラムに反映させるのは拙速であると思っていて、まずは、日よけの効果算出ツールにそれを適用させるのが先かなと思っています。
https://shading-house.beta.lowenergy.jp/
現行では、上下左右にある「ボックス型」と左右にある「サイドフィン型」がありますが、上下のみにあるような形状は入力できないです。これは、日よけの内側の反射を考慮していないため、上下のみにあるような形状はオーバーハング型でOKでしょ？という思想かと思います。これをどうするのか？という議論を詰めた上で、「日よけの効果係数」の定義を整理した上で、負荷計算に導入するのが良いかと思います。
「日よけの効果係数」の定義をきちっと議論しないまま、負荷計算にだけ導入するのは、全体の整合性が崩れるため、あまりよろしくないのでは？というのが僕の意見です。
