### ISSUE TITLE
窓の吸収日射熱取得の項を追加する

### ISSUE THREAD

**Issue by satoh-er** [BRI-EES-House/heat_load_calc#7]
# 概要
窓の透過率＝日射熱取得率となっているので、吸収日射熱取得の項を追加する。（当面はゼロ）
対象はa11_opening_transmission_solar_radiation.py

# タスク
- [ ] 集約化についてドキュメント化する
- [ ] コードに反映させる

# 参考情報
（ここに添付ファイル・画像・URL等を貼り付ける）

**Comment by HisashiMiura** [comment]
@satoh-er これって、窓への吸収分はどうやってのせるんでしたっけ？相当外気温度として反映させるんでしょうか・・・？

**Comment by satoh-er** [comment]
相当外気温度にのせる予定でしたが、集約が入るのでペンディングでした。
少し考えてみます。
