### ISSUE TITLE
永田の方式による放射熱伝達率のテスト

### ISSUE THREAD

**Issue by satoh-er** [BRI-EES-House/heat_load_calc#81]
# 概要
（ここに概要を記す）

# タスク
- [ ] （ここにタスクを記す）
- [ ] （ここにタスクを記す）

# 参考情報
（ここに添付ファイル・画像・URL等を貼り付ける）

**Comment by satoh-er** [comment]
@HisashiMiura 
永田先生の放射熱伝達について、2次元を仮定しJupyter Notebookで結果をグラフ表示しました。
同時に、表面温度を仮定し、放射熱収支がゼロとなることを確認しました。
フォルダ名称変更のプルリクエスト（change_folder_name）が通ったら、test_multizoneでエクセル計算した結果と比較してみる予定です。

**Comment by HisashiMiura** [comment]
@satoh-er エクセルとずれ・・・とありますが、そのエクセルってどこにありますか？

**Comment by satoh-er** [comment]
エクセルとPythonの収束条件が異なるのが要因かと思います。
両者を厳しくして試してみます。
念のためエクセル版を以下に入れました。
test\test_multizone\永田先生の放射計算正解値.xlsx

**Comment by satoh-er** [comment]
手計算とPythonの条件を統一し、テストが通ることを確認
